'use client'
import { useState, useEffect } from 'react'
import Link from 'next/link'

export default function Students() {
  const [students, setStudents] = useState<any[]>([])
  const [file, setFile] = useState<File | null>(null)
  const [loading, setLoading] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [search, setSearch] = useState('')
  const [uploadError, setUploadError] = useState('')
  const [expandedFees, setExpandedFees] = useState<number | null>(null)

  async function downloadCertificate(studentId: number, studentName: string) {
    const res = await fetch('/api/certificate?studentId=' + studentId)
    const data = await res.json()
    const { jsPDF } = await import('jspdf')
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const w = 210
    doc.setDrawColor(10, 31, 78)
    doc.setLineWidth(4)
    doc.line(20, 15, w - 20, 15)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(16)
    doc.setTextColor(10, 31, 78)
    doc.text(data.school.name.toUpperCase(), w / 2, 30, { align: 'center' })
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(120, 120, 120)
    doc.text(data.school.term, w / 2, 38, { align: 'center' })
    doc.setDrawColor(200, 200, 200)
    doc.setLineWidth(0.3)
    doc.line(20, 44, w - 20, 44)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(10, 31, 78)
    doc.text('FEE CLEARANCE CERTIFICATE', w / 2, 58, { align: 'center' })
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(80, 80, 80)
    doc.text('This certifies that the student below has settled all fee', w / 2, 70, { align: 'center' })
    doc.text('obligations for the current academic term.', w / 2, 77, { align: 'center' })
    const rows = [
      ['Student Name', data.student.name],
      ['Admission No', data.student.admNo],
      ['Class', data.student.class + ' ' + data.student.stream],
      ['Fee Required', 'KES ' + data.student.feeRequired.toLocaleString()],
      ['Total Paid', 'KES ' + data.student.totalPaid.toLocaleString()],
      ['Outstanding Balance', 'KES 0'],
    ]
    let y = 92
    rows.forEach(([label, value]) => {
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(120, 120, 120)
      doc.setFontSize(9)
      doc.text(label, 40, y)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(20, 20, 20)
      doc.setFontSize(10)
      doc.text(value, 105, y)
      doc.setDrawColor(230, 230, 230)
      doc.setLineWidth(0.2)
      doc.line(40, y + 3, w - 40, y + 3)
      y += 14
    })
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(10, 31, 78)
    doc.text('Status: CLEARED', w / 2, y + 10, { align: 'center' })
    doc.setDrawColor(10, 31, 78)
    doc.setLineWidth(0.4)
    doc.line(40, 230, 90, 230)
    doc.line(120, 230, 170, 230)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(100, 100, 100)
    doc.text('Bursar', 65, 236, { align: 'center' })
    doc.text('Principal', 145, 236, { align: 'center' })
    doc.text(data.school.name, 65, 242, { align: 'center' })
    doc.text(data.school.name, 145, 242, { align: 'center' })
    doc.setDrawColor(10, 31, 78)
    doc.setLineWidth(4)
    doc.line(20, 270, w - 20, 270)
    doc.setFontSize(8)
    doc.setTextColor(160, 160, 160)
    const dateStr = new Date().toLocaleDateString('en-KE')
    doc.text('Generated by FeeTracker · ' + dateStr, w / 2, 278, { align: 'center' })
    doc.save(studentName.replace(/\s+/g, '_') + '_clearance.pdf')
    return { data }
  }

  function shareViaWhatsApp(student: any, data: any) {
    const msg = `Dear ${student.parentName || 'Parent'}, this is to confirm that ${student.name} (${student.class} ${student.stream || ''}) has been CLEARED of all fee obligations for the current term at ${data.school.name}. Total paid: KES ${data.student.totalPaid.toLocaleString()}. Please retain this message as your clearance confirmation. - FeeTracker`
    const phone = student.parentPhone
      ? '254' + student.parentPhone.replace(/\s/g, '').replace(/^0/, '')
      : ''
    if (phone) {
      window.open('https://wa.me/' + phone + '?text=' + encodeURIComponent(msg), '_blank')
    }
  }

  useEffect(() => {
    fetchStudents()
  }, [])

  async function fetchStudents() {
    setLoading(true)
    const res = await fetch('/api/students')
    const data = await res.json()
    setStudents(data)
    setLoading(false)
  }

  async function handleUpload() {
    if (!file) return
    setUploading(true)
    setUploadError('')
    const formData = new FormData()
    formData.append('file', file)
    const res = await fetch('/api/students', { method: 'POST', body: formData })
    const data = await res.json()
    if (!res.ok) {
      setUploadError(data.error || 'Upload failed')
      setUploading(false)
      return
    }
    setFile(null)
    await fetchStudents()
    setUploading(false)
  }

  const filtered = students.filter(s =>
    s.name.toLowerCase().includes(search.toLowerCase()) ||
    (s.admNo || '').toLowerCase().includes(search.toLowerCase()) ||
    (s.class || '').toLowerCase().includes(search.toLowerCase())
  )

  function hasFeeBreakdown(s: any) {
    return s.tuitionFee > 0 || s.sportsFee > 0 || s.clubsFee > 0 || s.otherFee > 0
  }

  return (
    <div style={{background: '#f8f9fc', minHeight: '100vh', fontFamily: 'Arial, sans-serif'}}>
      <style>{`
        @media (max-width: 640px) {
          .stu-header { flex-direction: column !important; align-items: flex-start !important; gap: 12px !important; padding: 16px !important; }
          .stu-header-actions { flex-wrap: wrap; width: 100%; }
          .stu-content { padding: 16px !important; }
          .stu-import-row { flex-direction: column !important; }
          .stu-search-row { flex-direction: column !important; align-items: flex-start !important; gap: 8px !important; }
          .stu-search-row input { width: 100% !important; }
          .stu-table-wrap { overflow-x: auto; -webkit-overflow-scrolling: touch; }
        }
      `}</style>

      <div className="stu-header" style={{background: '#0a1f4e', padding: '24px 32px', display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
        <div>
          <h1 style={{fontSize: '20px', fontWeight: 700, color: '#fff', fontFamily: 'Georgia, serif', marginBottom: '3px'}}>Students</h1>
          <p style={{fontSize: '12px', color: '#94a3c8'}}>{students.length} students enrolled</p>
        </div>
        <div className="stu-header-actions" style={{display: 'flex', gap: '10px', alignItems: 'center'}}>
          <Link href="/dashboard" style={{border: '1px solid rgba(255,255,255,0.2)', color: '#fff', padding: '8px 16px', borderRadius: '5px', fontSize: '12px', textDecoration: 'none'}}>
            ← Dashboard
          </Link>
        </div>
      </div>

      <div className="stu-content" style={{padding: '24px 32px'}}>
        <div style={{background: '#fff', borderRadius: '8px', border: '1px solid #e2e8f0', padding: '20px', marginBottom: '16px'}}>
          <h2 style={{fontSize: '14px', fontWeight: 700, color: '#0f172a', marginBottom: '4px'}}>Import students</h2>
          <p style={{fontSize: '12px', color: '#94a3b8', marginBottom: '4px'}}>
            CSV columns: name, admNo, class, stream, feeRequired, parentName, parentPhone
          </p>
          <p style={{fontSize: '11px', color: '#94a3b8', marginBottom: '16px'}}>
            Optional fee breakdown columns: <em>Tuition Fee, Sports Fee, Clubs Fee, Other Fee</em> — if provided, feeRequired is calculated as their sum.
          </p>
          {uploadError && (
            <div style={{background: '#fcebeb', border: '1px solid #f5c6c6', color: '#a32d2d', fontSize: '12px', padding: '10px 12px', borderRadius: '6px', marginBottom: '12px'}}>
              {uploadError}
            </div>
          )}
          <div className="stu-import-row" style={{display: 'flex', gap: '10px', alignItems: 'center'}}>
            <input
              type="file"
              accept=".csv,.xlsx,.xls"
              style={{fontSize: '13px', color: '#64748b', flex: 1}}
              onChange={e => { setFile(e.target.files?.[0] || null); setUploadError('') }}
            />
            <button
              onClick={handleUpload}
              disabled={!file || uploading}
              style={{
                background: (!file || uploading) ? '#94a3b8' : '#0a1f4e',
                color: '#fff', padding: '8px 16px', borderRadius: '6px', fontSize: '13px', fontWeight: 700,
                border: 'none', cursor: (!file || uploading) ? 'not-allowed' : 'pointer', whiteSpace: 'nowrap'
              }}
            >
              {uploading ? 'Uploading...' : 'Import'}
            </button>
          </div>
        </div>

        <div style={{background: '#fff', borderRadius: '8px', border: '1px solid #e2e8f0'}}>
          <div className="stu-search-row" style={{padding: '14px 16px', borderBottom: '1px solid #f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '12px'}}>
            <h2 style={{fontSize: '13px', fontWeight: 700, color: '#0f172a', whiteSpace: 'nowrap'}}>All students</h2>
            <input
              type="text"
              placeholder="Search by name, admission no..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              style={{border: '1px solid #e2e8f0', borderRadius: '6px', padding: '6px 12px', fontSize: '12px', width: '240px', outline: 'none'}}
            />
          </div>

          {loading ? (
            <div style={{textAlign: 'center', color: '#94a3b8', padding: '48px'}}>Loading...</div>
          ) : filtered.length === 0 ? (
            <div style={{textAlign: 'center', color: '#94a3b8', padding: '48px', fontSize: '13px'}}>
              {students.length === 0 ? 'No students yet. Import a CSV to get started.' : 'No students match your search.'}
            </div>
          ) : (
            <div className="stu-table-wrap">
              <table style={{width: '100%', borderCollapse: 'collapse' as const, fontSize: '12px'}}>
                <thead>
                  <tr style={{textAlign: 'left' as const, borderBottom: '1px solid #f1f5f9'}}>
                    {['Name', 'Adm No', 'Class', 'Fee Required', 'Paid', 'Balance', 'Status', ''].map(h => (
                      <th key={h} style={{padding: '10px 14px', color: '#94a3b8', fontWeight: 500, fontSize: '10px', textTransform: 'uppercase' as const, letterSpacing: '0.5px', whiteSpace: 'nowrap'}}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filtered.map(student => {
                    const paid = student.payments.reduce((sum: number, p: any) => sum + p.amount, 0)
                    const balance = student.feeRequired - paid
                    const cleared = balance <= 0
                    const showFees = expandedFees === student.id
                    return (
                      <>
                        <tr key={student.id} style={{borderBottom: showFees ? 'none' : '1px solid #f8fafc'}}>
                          <td style={{padding: '10px 14px', fontWeight: 600, color: '#0f172a', whiteSpace: 'nowrap'}}>
                            {student.name}
                            {hasFeeBreakdown(student) && (
                              <button
                                onClick={() => setExpandedFees(showFees ? null : student.id)}
                                style={{marginLeft: '6px', fontSize: '10px', color: '#c8a84b', background: 'none', border: 'none', cursor: 'pointer', padding: 0}}
                              >
                                {showFees ? '▲ fees' : '▼ fees'}
                              </button>
                            )}
                          </td>
                          <td style={{padding: '10px 14px', color: '#64748b'}}>{student.admNo || '—'}</td>
                          <td style={{padding: '10px 14px', color: '#64748b', whiteSpace: 'nowrap'}}>{student.class} {student.stream}</td>
                          <td style={{padding: '10px 14px', whiteSpace: 'nowrap'}}>KES {student.feeRequired.toLocaleString()}</td>
                          <td style={{padding: '10px 14px', color: '#0a1f4e', fontWeight: 600, whiteSpace: 'nowrap'}}>KES {paid.toLocaleString()}</td>
                          <td style={{padding: '10px 14px', color: balance > 0 ? '#e24b4a' : '#64748b', fontWeight: balance > 0 ? 600 : 400, whiteSpace: 'nowrap'}}>
                            KES {balance.toLocaleString()}
                          </td>
                          <td style={{padding: '10px 14px'}}>
                            <span style={{
                              background: cleared ? '#e1f5ee' : paid > 0 ? '#fef9ec' : '#fcebeb',
                              color: cleared ? '#0a1f4e' : paid > 0 ? '#92681a' : '#a32d2d',
                              fontSize: '10px', padding: '3px 8px', borderRadius: '999px', fontWeight: 600, whiteSpace: 'nowrap'
                            }}>
                              {cleared ? 'Cleared' : paid > 0 ? 'Partial' : 'Unpaid'}
                            </span>
                          </td>
                          <td style={{padding: '10px 14px'}}>
                            {cleared && (
                              <div style={{display: 'flex', gap: '6px'}}>
                                <button
                                  onClick={async () => {
                                    const result = await downloadCertificate(student.id, student.name)
                                    if (result) shareViaWhatsApp(student, result.data)
                                  }}
                                  style={{fontSize: '11px', color: '#c8a84b', background: 'none', border: '1px solid #c8a84b', padding: '3px 8px', borderRadius: '4px', cursor: 'pointer', fontWeight: 600, whiteSpace: 'nowrap'}}
                                >
                                  Certificate
                                </button>
                              </div>
                            )}
                          </td>
                        </tr>
                        {showFees && hasFeeBreakdown(student) && (
                          <tr key={student.id + '-fees'} style={{borderBottom: '1px solid #f8fafc', background: '#fafbfc'}}>
                            <td colSpan={8} style={{padding: '0 14px 12px 28px'}}>
                              <div style={{display: 'flex', gap: '16px', flexWrap: 'wrap'}}>
                                {student.tuitionFee > 0 && <span style={{fontSize: '11px', color: '#64748b'}}>Tuition: <strong>KES {student.tuitionFee.toLocaleString()}</strong></span>}
                                {student.sportsFee > 0 && <span style={{fontSize: '11px', color: '#64748b'}}>Sports: <strong>KES {student.sportsFee.toLocaleString()}</strong></span>}
                                {student.clubsFee > 0 && <span style={{fontSize: '11px', color: '#64748b'}}>Clubs: <strong>KES {student.clubsFee.toLocaleString()}</strong></span>}
                                {student.otherFee > 0 && <span style={{fontSize: '11px', color: '#64748b'}}>Other: <strong>KES {student.otherFee.toLocaleString()}</strong></span>}
                              </div>
                            </td>
                          </tr>
                        )}
                      </>
                    )
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
