'use client'
import { useState, useEffect } from 'react'
import Link from 'next/link'

export default function Students() {
  const [students, setStudents] = useState<any[]>([])
  const [file, setFile] = useState<File | null>(null)
  const [loading, setLoading] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [search, setSearch] = useState('')

  async function downloadCertificate(studentId: number, studentName: string) {
  const res = await fetch('/api/certificate?studentId=' + studentId)
  const data = await res.json()

  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const w = 210

  // Top border line
  doc.setDrawColor(10, 31, 78)
  doc.setLineWidth(4)
  doc.line(20, 15, w - 20, 15)

  // School name
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(10, 31, 78)
  doc.text(data.school.name.toUpperCase(), w / 2, 30, { align: 'center' })

  // Term
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(120, 120, 120)
  doc.text(data.school.term, w / 2, 38, { align: 'center' })

  // Thin divider
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.3)
  doc.line(20, 44, w - 20, 44)

  // Certificate title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(10, 31, 78)
  doc.text('FEE CLEARANCE CERTIFICATE', w / 2, 58, { align: 'center' })

  // Body text
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(80, 80, 80)
  doc.text('This certifies that the student below has settled all fee', w / 2, 70, { align: 'center' })
  doc.text('obligations for the current academic term.', w / 2, 77, { align: 'center' })

  // Student details
  const rows = [
    ['Student Name', data.student.name],
    ['Admission No', data.student.admNo],
    ['Class', data.student.class + ' ' + data.student.stream],
    ['Fee Required', 'KES ' + data.student.feeRequired.toLocaleString()],
    ['Total Paid', 'KES ' + data.student.totalPaid.toLocaleString()],
    ['Outstanding Balance', 'KES 0'],
  ]

  let y = 92
  rows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(120, 120, 120)
    doc.setFontSize(9)
    doc.text(label, 40, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(20, 20, 20)
    doc.setFontSize(10)
    doc.text(value, 105, y)
    doc.setDrawColor(230, 230, 230)
    doc.setLineWidth(0.2)
    doc.line(40, y + 3, w - 40, y + 3)
    y += 14
  })

  // Cleared text
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(10, 31, 78)
  doc.text('Status: CLEARED', w / 2, y + 10, { align: 'center' })

  // Signature lines
  doc.setDrawColor(10, 31, 78)
  doc.setLineWidth(0.4)
  doc.line(40, 230, 90, 230)
  doc.line(120, 230, 170, 230)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  doc.text('Bursar', 65, 236, { align: 'center' })
  doc.text('Principal', 145, 236, { align: 'center' })

  // Bottom border line
  doc.setDrawColor(10, 31, 78)
  doc.setLineWidth(4)
  doc.line(20, 270, w - 20, 270)

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(160, 160, 160)
  doc.text(
    'Generated by FeeTracker · ' + new Date().toLocaleDateString('en-KE', { day: 'numeric', month: 'long', year: 'numeric' }),
    w / 2, 278, { align: 'center' }
  )

  doc.save(studentName.replace(/ /g, '_') + '_clearance.pdf')
}
  useEffect(() => {
    fetchStudents()
  }, [])

  async function fetchStudents() {
    setLoading(true)
    const res = await fetch('/api/students')
    const data = await res.json()
    setStudents(data)
    setLoading(false)
  }

  async function handleUpload() {
    if (!file) return
    setUploading(true)
    const formData = new FormData()
    formData.append('file', file)
    formData.append('schoolId', '1')
    await fetch('/api/students', { method: 'POST', body: formData })
    await fetchStudents()
    setFile(null)
    setUploading(false)
  }

  const filtered = students.filter(s =>
    s.name.toLowerCase().includes(search.toLowerCase()) ||
    s.class.toLowerCase().includes(search.toLowerCase()) ||
    s.admNo.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-6xl mx-auto p-6">
        <div className="flex items-center gap-4 mb-6">
          <Link href="/dashboard" className="text-gray-400 hover:text-gray-600 text-sm">← Back</Link>
          <h1 className="text-2xl font-semibold text-gray-900">Students</h1>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-4 mb-4">
          <h2 className="font-medium text-gray-900 mb-1">Upload student list</h2>
          <p className="text-sm text-gray-400 mb-3">
            Your Excel file should have columns: Adm No, Name, Class, Stream, Parent Name, Parent Phone, Fee Required
          </p>
          <div className="flex gap-3">
            <input
              type="file"
              accept=".xlsx,.xls,.csv"
              onChange={e => setFile(e.target.files?.[0] || null)}
              className="text-sm text-gray-500 border border-gray-200 rounded-lg px-3 py-1.5"
            />
            <button
              onClick={handleUpload}
              disabled={!file || uploading}
              className="text-white px-4 py-1.5 rounded-lg text-sm disabled:opacity-50"
              style={{backgroundColor: '#0a1f4e'}}
            >
              {uploading ? 'Uploading...' : 'Upload'}
            </button>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-gray-200">
          <div className="p-4 border-b border-gray-100 flex justify-between items-center">
            <h2 className="font-medium text-gray-900">{students.length} students</h2>
            <input
              className="border border-gray-200 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-900 w-48"
              placeholder="Search name or class..."
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
          </div>
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs text-gray-400 uppercase tracking-wide border-b border-gray-100">
                <th className="p-3">Adm No</th>
                <th className="p-3">Name</th>
                <th className="p-3">Class</th>
                <th className="p-3">Parent phone</th>
                <th className="p-3">Fee required</th>
                <th className="p-3">Paid</th>
                <th className="p-3">Balance</th>
                <th className="p-3">Status</th>
                <th className="p-3">Certificate</th>
              </tr>
            </thead>
            <tbody>
              {loading && (
                <tr><td colSpan={9} className="p-4 text-center text-gray-400">Loading...</td></tr>
              )}
              {!loading && filtered.length === 0 && (
                <tr><td colSpan={9} className="p-4 text-center text-gray-400">No students yet. Upload a student list to get started.</td></tr>
              )}
              {filtered.map(student => {
                const paid = student.payments.reduce((sum: number, p: any) => sum + p.amount, 0)
                const balance = student.feeRequired - paid
                const status = balance <= 0 ? 'Paid' : paid > 0 ? 'Partial' : 'Unpaid'
                const statusColor = status === 'Paid' ? 'bg-green-100 text-green-700' : status === 'Partial' ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-700'
                return (
                  <tr key={student.id} className="border-b border-gray-50 hover:bg-gray-50">
                    <td className="p-3 text-gray-400">{student.admNo}</td>
                    <td className="p-3 font-medium">{student.name}</td>
                    <td className="p-3 text-gray-500">{student.class} {student.stream}</td>
                    <td className="p-3 text-gray-500">{student.parentPhone || '—'}</td>
                    <td className="p-3">KES {student.feeRequired.toLocaleString()}</td>
                    <td className="p-3 text-green-700">KES {paid.toLocaleString()}</td>
                    <td className="p-3 text-amber-600">KES {balance.toLocaleString()}</td>
                    <td className="p-3">
                      <span className={'text-xs px-2 py-1 rounded-full font-medium ' + statusColor}>
                        {status}
                      </span>
                    </td>
                    <td className="p-3">
                      {status === 'Paid' && (
                        <button
                          onClick={() => downloadCertificate(student.id, student.name)}
                          className="text-xs border border-green-300 text-green-700 px-2 py-1 rounded-lg hover:bg-green-50"
                        >
                          Certificate
                        </button>
                      )}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}